### ISSUE TITLE
Check that raw data are available on start and warn user if not reads were found

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/chipseq-smk-pipeline#3]
The following command line fails on franklin:
```
cd /mnt/stripe/shpynov/chipseq-smk-pipeline
source activate snakemake
snakemake all --use-conda --cores 28  --config work_dir=/mnt/stripe/bio/raw-data/geo-samples/GSE53643 fastq_dir=/mnt/stripe/bio/raw-data/geo-samples/GSE53643/fastq genome=mm10 macs2_params="-q 0.05" span_bin=100 span_fdr=0.05 -n
```

But fastq_dir contains a lot of fastq files.

**Comment by olegs** [comment]
When I launch it, I get the following error:
```
Activating conda environment: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/9cb9ec03
Traceback (most recent call last):
  File "/mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/scripts/tmpnu465fyp.wrapper.py", line 24, in <module>
    "multiqc"
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 133, in __new__
Traceback (most recent call last):
  File "/mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/scripts/tmp9wm3eu1q.wrapper.py", line 24, in <module>
    "multiqc"
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 133, in __new__
Traceback (most recent call last):
  File "/mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/scripts/tmp35cf9cpc.wrapper.py", line 24, in <module>
    "multiqc"
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 133, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  multiqc  --force -o multiqc/bam_filtered -n multiqc.html   > multiqc/bam_filtered/multiqc.log 2>&1 ' returned no
n-zero exit status 2.
    raise sp.CalledProcessError(retcode, cmd)
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  multiqc  --force -o multiqc/fastqc -n multiqc.html   > multiqc/fastqc/multiqc.log 2>&1 ' returned non-zero exit
status 2.
subprocess.CalledProcessError: Command ' set -euo pipefail;  multiqc  --force -o multiqc/bam_raw -n multiqc.html   > multiqc/bam_raw/multiqc.log 2>&1 ' returned non-zero exi
t status 2.
[Sat Oct 19 13:29:31 2019]
Error in rule bam_raw_multiqc:
    jobid: 2
    output: multiqc/bam_raw/multiqc.html
    log: multiqc/bam_raw/multiqc.log
    conda-env: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/9cb9ec03
[Sat Oct 19 13:29:31 2019]

Error in rule multiqc_fastq:
    jobid: 1
    output: multiqc/fastqc/multiqc.html
    log: multiqc/fastqc/multiqc.log
    conda-env: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/9cb9ec03
```

**Comment by olegs** [comment]
Well it turned out that It happened due to the hidden parameter in `config.yaml`: `fastq_ext`.

**Comment by iromeo** [comment]
We could add some validation in `onstart` block, e.g. like we have in wgbs pipeline

**Comment by olegs** [comment]
That would be nice, because this option is not reflected in README.md.

**Comment by iromeo** [comment]
Yes, pipeline is in a beta state, not polished at the moment.
