### ISSUE TITLE
Bowtie fails

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/chipseq-smk-pipeline#4]
```
Activating conda environment: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/a30ef292
Traceback (most recent call last):
  File "/mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/scripts/tmpuscfchbw.wrapper.py", line 25, in <module>
    "(bowtie2 --threads {snakemake.threads} {snakemake.params.extra} "
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 133, in __new__
Traceback (most recent call last):
  File "/mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/scripts/tmpbjbxtwx7.wrapper.py", line 25, in <module>
    "(bowtie2 --threads {snakemake.threads} {snakemake.params.extra} "
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 133, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  (bowtie2 --threads 4  -x bowtie2-index/mm10 -U /mnt/stripe/bio/raw-data/geo-samples/GSE53643/fastq/GSM1297956.fa
stq | samtools view -Sbh -o bams/GSM1297956.bam.raw -)  > logs/bam_raw/bowtie2/GSM1297956.log 2>&1 ' returned non-zero exit status 1.
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  (bowtie2 --threads 4  -x bowtie2-index/mm10 -U /mnt/stripe/bio/raw-data/geo-samples/GSE53643/fastq/GSM1297966.fa
stq | samtools view -Sbh -o bams/GSM1297966.bam.raw -)  > logs/bam_raw/bowtie2/GSM1297966.log 2>&1 ' returned non-zero exit status 1.
[Sat Oct 19 16:30:02 2019]
[Sat Oct 19 16:30:02 2019]
Error in rule bowtie2_align_single:
Error in rule bowtie2_align_single:
    jobid: 465
    jobid: 483
    output: bams/GSM1297956.bam.raw
    output: bams/GSM1297966.bam.raw
    log: logs/bam_raw/bowtie2/GSM1297956.log
    log: logs/bam_raw/bowtie2/GSM1297966.log
    conda-env: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/a30ef292
    conda-env: /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/a30ef292


RuleException:
CalledProcessError in line 57 of /mnt/stripe/shpynov/chipseq-smk-pipeline/rules/alignment.smk:
Command 'source activate /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.snakemake/conda/a30ef292; set -euo pipefail;  python /mnt/stripe/bio/raw-data/geo-samples/GSE53643/.s
nakemake/scripts/tmpuscfchbw.wrapper.py ' returned non-zero exit status 1.
  File "/mnt/stripe/shpynov/chipseq-smk-pipeline/rules/alignment.smk", line 57, in __rule_bowtie2_align_single
  File "/home/user/anaconda/envs/snakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```

**Comment by olegs** [comment]
Happened while running:
```
cd /mnt/stripe/shpynov/chipseq-smk-pipeline
snakemake all --use-conda --cores 28  --config work_dir=/mnt/stripe/bio/raw-data/geo-samples/GSE53643 fastq_dir=/mnt/stripe/bio/raw-data/geo-samples/GSE53643/fastq genome=mm10 macs2_params="-q 0.05" span_bin=100 span_fdr=0.05
```

**Comment by iromeo** [comment]
Seems something wrong with your data:

```
Error: Read SRR1058953.1 1_2_680_F3 length=35 has more quality values than read characters.
Error: Read SRR1058953.17 1_6_775_F3 length=35 has more quality values than read characters.
terminate called after throwing an instance of 'int'
terminate called recursively
(ERR): bowtie2-align died with signal 6 (ABRT)
/mnt/stripe/bio/raw-data/geo-samples/GSE53643/logs/bam_raw/bowtie2/GSM1297966.log (END)
```

**Comment by iromeo** [comment]
`$head /mnt/stripe/bio/raw-data/geo-samples/GSE53643/fastq//GSM1297966.fastq`
```
@SRR1058953.1 1_2_680_F3 length=35
T0.0120.3321.0302.301.2202.2221.102.
+SRR1058953.1 1_2_680_F3 length=35
!@!@@?@!>>@@!@@@@!<?@!?/@@!@@2@!@@@!
@SRR1058953.2 1_2_1135_F3 length=35
T3.0211.2120.3232.120.0022.3212.031.
+SRR1058953.2 1_2_1135_F3 length=35
!@!@@@@!88@@!@@@8!<@@!=@?@!>8@@!8@@!
```

**Comment by iromeo** [comment]
Your raw data is in `ABI SOLiD` color space, which isn't expected by majority of tools. Please use dump your data in letter base format. Also is convenient to dump directly in *.gz, it requires much less HDD space (see fastq-dump options)
